/**
 * TypeScript types for the Google Pay UCP handler configuration.
 * Based on https://pay.google.com/gp/p/ucp/2026-01-11/schemas/config.json
 */

/** Identity details for the merchant as required by the Google Pay UCP handler */
export interface GpayMerchantInfo {
  /** The user-facing name of the merchant that will appear on the Google Pay payment sheet */
  merchant_name?: string;
  /** The Google Pay Merchant ID. Use a dummy value or 'TEST' for TEST environment */
  merchant_id: string;
  /** The fully qualified domain name where the checkout occurs, used for origin validation */
  merchant_origin?: string;
  /** An optional authorization JWT for certain integration contexts */
  auth_jwt?: string;
}

/**
 * Supported authentication methods for Google Pay CARD payments.
 * See: https://developers.google.com/pay/api/web/reference/request-objects#AuthenticationMethod
 *
 * - PAN_ONLY: Card number is provided only (no cryptogram).
 * - CRYPTOGRAM_3DS: 3-D Secure cryptogram generated by issuer.
 */
export type GpayAllowedAuthMethods = 'PAN_ONLY' | 'CRYPTOGRAM_3DS';

/**
 * Supported card networks for Google Pay CARD payments.
 * See: https://developers.google.com/pay/api/web/reference/request-objects#CardNetwork
 *
 * - AMEX: American Express
 * - DISCOVER: Discover
 * - INTERAC: Interac (Canada)
 * - JCB: JCB (Japan Credit Bureau)
 * - MASTERCARD: Mastercard
 * - VISA: Visa
 */
export type GpayAllowedCardNetworks =
  | 'AMEX'
  | 'DISCOVER'
  | 'INTERAC'
  | 'JCB'
  | 'MASTERCARD'
  | 'VISA';

/** Parameters for the CARD payment method (CardParameters) */
export interface GpayCardParameters {
  allowed_auth_methods?: GpayAllowedAuthMethods[];
  allowed_card_networks?: GpayAllowedCardNetworks[];
}

/** Tokenization specification parameters (gateway-specific) */
export type GpayTokenizationParameters = Record<string, unknown>;

export type GpayTokenizationType = 'DIRECT' | 'PAYMENT_GATEWAY';

/** Configure an account or decryption provider to receive payment information */
export interface GpayTokenizationSpecification {
  type: GpayTokenizationType;
  parameters: GpayTokenizationParameters;
}

/** Configuration options for an allowed payment method */
export interface GpayPaymentMethod {
  type: 'CARD';
  parameters: GpayCardParameters;
  /** Required for CARD payment method. Configure tokenization provider */
  tokenization_specification?: GpayTokenizationSpecification;
}

/**
 * Google Pay Environment
 *
 * 'TEST': Use the Google Pay test environment for integration and sandbox transactions.
 * 'PRODUCTION': Use the live Google Pay production environment for real transactions.
 */
export type GpayEnvironment = 'TEST' | 'PRODUCTION';

/** Configuration schema for the com.google.pay payment handler */
export interface GpayConfig {
  /** The major Google Pay API version. Currently, this must be 2 */
  api_version: 2;
  /** The minor Google Pay API version. Currently, this must be 0 */
  api_version_minor: 0;
  /** The Google Pay environment */
  environment?: GpayEnvironment;
  /** Identity details for the merchant as required by the Google Pay UCP handler */
  merchant_info: GpayMerchantInfo;
  /** The payment methods allowed for this transaction */
  allowed_payment_methods: GpayPaymentMethod[];
}
